import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic"],
  weight: ["200", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "قلم | خدمات قضایی و اینترنتی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-ir">
      <body className={`${vazirmatn.variable}  antialiased`}>{children}</body>
    </html>
  );
}
